version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: bkuhlmann/ruby:latest
    steps:
      - checkout

      - restore_cache:
          name: Bundler Restore
          keys:
            - gem-cache-{{.Branch}}-{{checksum "gemsmith.gemspec"}}
            - gem-cache-

      - run:
          name: Bundler Install
          command: |
            gem update --system
            bundle config set path "vendor/bundle"
            gem install rails
            bundle install

      - save_cache:
          name: Bundler Store
          key: gem-cache-{{.Branch}}-{{checksum "gemsmith.gemspec"}}
          paths:
            - vendor/bundle

      - run:
          name: Build
          command: |
            sed -i 's/ rubycritic//g' Rakefile
            bundle exec rake
