inherit_gem:
  caliber: config/all.yml

Gemspec/RequiredRubyVersion:
  Exclude:
    - "spec/support/fixtures/*.gemspec"
Layout/RedundantLineBreak:
  Exclude:
    - "spec/support/fixtures/*.gemspec"
Layout/EmptyLines:
  Exclude:
    - "spec/support/fixtures/test-minimum-security.gemspec"
    - "spec/support/fixtures/test-minimum.gemspec"
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "spec/support/fixtures/spec/lib/cli/shell_without_refinements_proof.rb"
Metrics/BlockLength:
  Exclude:
    - "lib/gemsmith/container.rb"
Metrics/CollectionLiteralLength:
  Exclude:
    - "lib/gemsmith/cli/commands/build.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/gemsmith/cli/shell.rb"
    - "lib/gemsmith/builders/documentation/readme.rb"
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/support/shared_contexts/application_dependencies.rb"
RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/support/fixtures/**/*"
RSpec/SpecFilePathSuffix:
  Exclude:
    - "spec/support/fixtures/**/*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/support/fixtures/**/*"
