---
:gem_platform: Gem::Platform::CURRENT
:author_name: "Testy Tester"
:author_email: "test@test.com"
:author_url: "https://www.test.com"
:gem_url: "https://www.gem.com"
:company_name: "ACME"
:company_url: "https://www.acme.com"
:github_user: "tester"
:year: 1920
:ruby_version: 2.0.0
:rails_version: 4.0.0
:post_install_message: "Follow @tester on Twitter for more info."
